/*CREACION TABLAS TEMPORALES*/
CREATE TABLE TEMP_CARGP1(
  INVENTO varchar(100),
  INVENTOR varchar(100),
  PROFESIONAL_ASIGNADO_INVENTO varchar(100),
  PROFESIONAL_JEFE_AREA varchar(100),
  PROFESIONAL_FECHA_CONTRATO varchar(100),
  SALARIO varchar(100),
  COMISION varchar(100),
  PROFESIONAL_AREA_INVESTIGACION varchar(100),
  RANKING varchar(10),
  INVENTO_ANIO varchar(10),
  INVENTO_PAIS  varchar(100),
  INVENTOR_PAIS varchar(100),
  REGION_PAIS varchar(100),
  CAPITAL varchar(100),
  POBLACION varchar(100),
  AREA_PAIS varchar(100),
  FRONTERA_CON varchar(100),
  NORTE varchar(5),
  SUR varchar(5),
  ESTE varchar(5),
  OESTE varchar(5)
);

CREATE TABLE TEMP_CARGP2(
    NOMBRE_ENCUESTA varchar(200),
    PREGUNTA varchar(1000),
    RESPUESTAS_POSIBLES varchar(500),
    RESPUESTA_CORRECTA varchar(500),
    PAIS VARCHAR(100),
    RESPUESTA_PAIS VARCHAR(5)
);

CREATE TABLE TEMP_CARGP3(
    NOMBRE_REGION varchar(100),
    REGION_PADRE varchar(100) DEFAULT NULL
);


