/*CARGA REGIONES*/
INSERT INTO region(NOMBRE_REGION) select NOMBRE_REGION FROM temp_cargp3;
UPDATE REGION R INNER JOIN (SELECT T.NOMBRE_REGION, R.ID_REGION FROM REGION R INNER JOIN temp_cargp3 T ON R.NOMBRE_REGION = T.REGION_PADRE) X ON X.NOMBRE_REGION = R.NOMBRE_REGION SET R.REGION_PADRE = X.ID_REGION;

/* CARGAR PAISES*/
INSERT INTO PAIS (NOMBRE, CAPITAL, POBLACION, AREA, ID_REGION) SELECT DISTINCT T.INVENTOR_PAIS, T.CAPITAL, T.POBLACION, T.AREA_PAIS, (SELECT R.ID_REGION FROM REGION R WHERE R.NOMBRE_REGION = T.REGION_PAIS) FROM temp_cargp1 T;
UPDATE temp_cargp2 SET PAIS = TRIM(PAIS);
INSERT INTO PAIS (NOMBRE, CAPITAL, POBLACION, AREA, ID_REGION) VALUES ('Belgica','Bruselas',11400000,30688,6);

/*cargar cardinal*/
INSERT INTO cardinal (CARDINAL) values('NORTE');
INSERT INTO cardinal (CARDINAL) values('SUR');
INSERT INTO cardinal (CARDINAL) values('ESTE');
INSERT INTO cardinal (CARDINAL) values('OESTE');

/*CARGA FRONTERAS */

INSERT INTO frontera(ID_PAIS_1, ID_PAIS_2, ID_CARDINAL)  SELECT distinct P1.ID, P2.ID, 1 from temp_cargp1 t INNER JOIN PAIS P1 ON P1.NOMBRE = T.INVENTOR_PAIS INNER JOIN PAIS P2 ON P2.NOMBRE = T.FRONTERA_CON where NORTE = 'X';
INSERT INTO frontera(ID_PAIS_1, ID_PAIS_2, ID_CARDINAL)  SELECT distinct P1.ID, P2.ID, 2 from temp_cargp1 t INNER JOIN PAIS P1 ON P1.NOMBRE = T.INVENTOR_PAIS INNER JOIN PAIS P2 ON P2.NOMBRE = T.FRONTERA_CON where SUR = 'X';
INSERT INTO frontera(ID_PAIS_1, ID_PAIS_2, ID_CARDINAL)  SELECT distinct P1.ID, P2.ID, 3 from temp_cargp1 t INNER JOIN PAIS P1 ON P1.NOMBRE = T.INVENTOR_PAIS INNER JOIN PAIS P2 ON P2.NOMBRE = T.FRONTERA_CON where ESTE = 'X';
INSERT INTO frontera(ID_PAIS_1, ID_PAIS_2, ID_CARDINAL)  SELECT distinct P1.ID, P2.ID, 4 from temp_cargp1 t INNER JOIN PAIS P1 ON P1.NOMBRE = T.INVENTOR_PAIS INNER JOIN PAIS P2 ON P2.NOMBRE = T.FRONTERA_CON where OESTE = 'X';

/*CARGA ENCUESTAS*/
INSERT INTO encuesta(NOMBRE)  SELECT DISTINCT T.NOMBRE_ENCUESTA FROM temp_cargp2 T;

/*CARGA PREGUNTA*/
insert into pregunta(PREGUNTA, ID_ENCUESTA)  select distinct T.PREGUNTA, E.ID from temp_cargp2 T INNER JOIN encuesta E ON E.NOMBRE = T.NOMBRE_ENCUESTA;

/*CARGA RESPUESTA*/
INSERT INTO RESPUESTA(RESPUESTA, ID_PREGUNTA)  SELECT DISTINCT T.RESPUESTAS_POSIBLES, P.ID FROM temp_cargp2 T INNER JOIN PREGUNTA P ON P.PREGUNTA = T.PREGUNTA;
UPDATE  RESPUESTA R inner join (select distinct r.id RES, P.ID PRE from temp_cargp2 T INNER JOIN pregunta p on T.PREGUNTA = p.PREGUNTA INNER JOIN respuesta r on r.RESPUESTA = t.RESPUESTA_CORRECTA and r.ID_PREGUNTA = p.ID) X  on R.ID = X.RES AND R.ID_PREGUNTA = X.PRE set CORRECTA = 1;

/*PAIS RESPUESTA*/
INSERT INTO PAIS_RESPUESTA(ID_PAIS, ID_PREGUNTA, ID_RESPUESTA)  SELECT DISTINCT P.ID, PR.ID, r.ID FROM temp_cargp2 T inner join PAIS P ON P.NOMBRE = T.PAIS INNER JOIN PREGUNTA PR ON PR.PREGUNTA = T.PREGUNTA INNER JOIN RESPUESTA r ON R.RESPUESTA LIKE CONCAT(T.RESPUESTA_PAIS, '.%') WHERE R.ID_PREGUNTA = PR.ID;

/*PROFESIONAL*/
INSERT INTO PROFESIONAL(NOMBRE, FECHA_CONTRATO, SALARIO, COMISION)  SELECT DISTINCT T.PROFESIONAL_ASIGNADO_INVENTO, STR_TO_DATE(T.PROFESIONAL_FECHA_CONTRATO,'%d/%m/%Y'), T.SALARIO, if(T.COMISION = '',0,t.COMISION) FROM temp_cargp1 T WHERE t.PROFESIONAL_ASIGNADO_INVENTO != '';

/*AREAS*/
INSERT INTO AREA(NOMBRE, RANKING)  SELECT DISTINCT T.PROFESIONAL_AREA_INVESTIGACION, T.RANKING FROM temp_cargp1 T where T.PROFESIONAL_AREA_INVESTIGACION != '';

/*profesional area*/
INSERT INTO profesional_area(ID_PROFESIONAL, ID_AREA, ES_JEFE)  SELECT DISTINCT P.ID, A.ID, 0 FROM temp_cargp1 T INNER JOIN PROFESIONAL P ON  P.NOMBRE = T.PROFESIONAL_ASIGNADO_INVENTO INNER JOIN AREA A ON A.NOMBRE = T.PROFESIONAL_AREA_INVESTIGACION  where T.PROFESIONAL_AREA_INVESTIGACION != '';
INSERT INTO profesional_area(ID_PROFESIONAL, ID_AREA, ES_JEFE)  SELECT distinct p.ID prof, a.ID ar, 1 FROM temp_cargp1 T INNER JOIN PROFESIONAL P ON  P.NOMBRE = T.PROFESIONAL_ASIGNADO_INVENTO INNER JOIN AREA A ON A.NOMBRE = T.PROFESIONAL_JEFE_AREA WHERE T.PROFESIONAL_JEFE_AREA != '';
INSERT INTO profesional_area(ID_PROFESIONAL, ID_AREA, ES_JEFE) SELECT DISTINCT P.ID, A.ID, 1 FROM temp_cargp1 T  INNER JOIN PROFESIONAL P ON  P.NOMBRE = T.PROFESIONAL_ASIGNADO_INVENTO, AREA A   WHERE T.PROFESIONAL_JEFE_AREA = 'TODAS' and not exists (select * from profesional_area where ID_PROFESIONAL = p.ID and ID_AREA = a.id);
UPDATE profesional_area SET ES_JEFE = 1 WHERE ID_PROFESIONAL = (SELECT DISTINCT P.ID FROM temp_cargp1 T INNER JOIN PROFESIONAL P ON P.NOMBRE = T.PROFESIONAL_ASIGNADO_INVENTO WHERE T.PROFESIONAL_JEFE_AREA = 'TODAS');

/*INVENTOR*/
INSERT INTO inventor(NOMBRE, ID_PAIS)  SELECT DISTINCT TRIM(T.INVENTOR), P.ID FROM temp_cargp1 T INNER JOIN PAIS P ON P.NOMBRE = T.INVENTOR_PAIS where t.INVENTOR != '';
/*invento*/
INSERT INTO INVENTO(NOMBRE, ANO, ID_PAIS, ID_PROFESIONAL)   select distinct T.INVENTO, STR_TO_DATE(T.INVENTO_ANIO,'%Y'), p.id, pr.id from temp_cargp1 t inner join pais p on p.NOMBRE = t.INVENTO_PAIS inner join profesional pr on pr.NOMBRE = t.PROFESIONAL_ASIGNADO_INVENTO;
 /*invento inventor*/
INSERT INTO invento_inventor(ID_INVENTO, ID_INVENTOR)  SELECT DISTINCT inv.id, ir.id FROM temp_cargp1 T inner join INVENTO INV ON INV.NOMBRE = INVENTO INNER JOIN INVENTOR IR ON IR.NOMBRE = INVENTOR;