DROP TABLE IF EXISTS TEMP_CARGP1;
DROP TABLE IF EXISTS TEMP_CARGP2;
DROP TABLE IF EXISTS TEMP_CARGP3;



DROP TABLE IF EXISTS invento_inventor CASCADE ;
DROP TABLE IF EXISTS INVENTOR CASCADE ;
DROP TABLE IF EXISTS INVENTO CASCADE ;
DROP TABLE IF EXISTS FRONTERA CASCADE ;
DROP TABLE IF EXISTS PAIS_RESPUESTA CASCADE ;
DROP TABLE IF EXISTS PAIS CASCADE ;
DROP TABLE IF EXISTS REGION CASCADE ;
DROP TABLE IF EXISTS CARDINAL CASCADE ;
DROP TABLE IF EXISTS RESPUESTA CASCADE ;
DROP TABLE IF EXISTS PREGUNTA CASCADE ;
DROP TABLE IF EXISTS ENCUESTA CASCADE ;
DROP TABLE IF EXISTS PROFESIONAL_AREA CASCADE ;
DROP TABLE IF EXISTS PROFESIONAL CASCADE ;
DROP TABLE IF EXISTS AREA CASCADE ;


